import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import YellowButton from "@/components/YellowButton";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>ვინ არის ჯაშუში?</h1>
        <Link>
          <YellowButton text="თამაშის დაწყება" />
        </Link>
      </main>
    </>
  );
}
